name: Bug Report
description: Report a bug that needs to be fixed on the site
title: "[Bug]: "
labels:
  - bug
  - needs-review
assignees:
  - anguspiv
projects:
  - anguspiv/11
  - anguspiv/5
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug!

  - type: textarea
    id: description
    attributes:
      label: Quick Description
      description: A clear and concise description of what the bug is.
      placeholder: When I click on X, Y happens instead of Z...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop images here...
    validations:
      required: false

  - type: dropdown
    id: browsers
    attributes:
      label: Browser
      description: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Microsoft Edge
        - Other
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      multiple: false
      options:
        - macOS
        - Windows
        - Linux
        - iOS
        - Android
        - Other
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Add any other context about the problem here
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: Add any related issues or documentation
      placeholder: |
        - Related to #123
        - See docs at https://...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our contribution guidelines
      options:
        - label: I have read the [CONTRIBUTING.md](../CONTRIBUTING.md)
          required: true
